# Site Settings
baseurl: ""
url : "https://gopikaharikumar.github.io"

# Blog Settings
theme_settings :
  title : Elixir

  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/hpp.png
    username : Gopika Harikumar
    description : 
   # experience :
      #- start : 2018-05-03
         
       # experience : company name, title
    skills : 
      - skill : Android & Java
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  gopikaharikumar8@gmail.com
    linkedin:  https://www.linkedin.com/in/gopikah/ 
    github: gopikaharikumar
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: gopikaharikumar
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
